### ISSUE TITLE
Better Logging

### ISSUE THREAD

**Issue by RustyDios** [tracktwo/EvacAll#1]
Is it possible to add a bool value to the dlc2info log statements, to turn off logging.
This will help an end user from needing to scroll through log lines. An example better log line given below.
Sorry if this is an incorrect way to do things. I suck at using GitHub

var config bool bEnableLogging;
~~
`Log("Adding EvacAll ability to template " $ CharTemplate.DataName, default.bEnableLogging, 'EvacAll');

**Comment by tracktwo** [comment]
I've addressed this in the EvacAll_WotC project. The vanilla mod hasn't been updated since wotc came out and I don't have things set up to rebuild the vanilla mod at the moment so I'm not going to make this change in vanilla unless it becomes super necessary.
